import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";

export type ActivityLogPdfRow = {
  createdAt: string;
  action: string;
  window: string;
  details: string;
};

export type ActivityLogPdfInput = {
  officeLabel: string;
  // Local calendar dates (YYYY-MM-DD), as picked in the dashboard filters.
  fromDate: string;
  toDate: string;
  filters: { window: string; action: string; search: string };
  generatedBy: string;
  summary: { totalQueueCreated: number; totalProcessed: number };
  rows: ActivityLogPdfRow[];
};

const MARGIN = 14;
const FOOTER_SPACE = 16;
const HEAD_FILL: [number, number, number] = [30, 41, 59];
const MUTED: [number, number, number] = [110, 110, 110];

// jsPDF's built-in fonts only cover Latin-1. Anything else (bullets, arrows,
// the narrow no-break space Intl puts before AM/PM) renders as garbage.
function pdfText(value: string): string {
  return value
    .replace(/[  -​ ]/g, " ")
    .replace(/•/g, "·")
    .replace(/→/g, "->")
    .replace(/[–—]/g, "-")
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[^\x00-\xFF]/g, "?");
}

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-PH", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function dayKey(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

function lastTableY(doc: jsPDF): number {
  return (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable
    .finalY;
}

export function buildActivityLogsPdf(input: ActivityLogPdfInput): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const tableMargin = { left: MARGIN, right: MARGIN, bottom: FOOTER_SPACE };

  const from = new Date(`${input.fromDate}T00:00:00`);
  const to = new Date(`${input.toDate}T00:00:00`);
  const rangeLabel =
    input.fromDate === input.toDate
      ? formatDate(from)
      : `${formatDate(from)} - ${formatDate(to)}`;

  // Starts a new page when fewer than `needed` mm remain, so a heading is
  // never left alone at the bottom of a page.
  const ensureSpace = (y: number, needed: number): number => {
    if (y + needed <= pageHeight - FOOTER_SPACE) return y;
    doc.addPage();
    return MARGIN + 4;
  };

  const sectionHeading = (title: string, y: number): number => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(20);
    doc.text(title, MARGIN, y);
    doc.setDrawColor(210);
    doc.line(MARGIN, y + 2, pageWidth - MARGIN, y + 2);
    return y + 7;
  };

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(20);
  doc.text("Activity Logs Report", MARGIN, 18);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text(pdfText(input.officeLabel), MARGIN, 24);

  autoTable(doc, {
    startY: 28,
    theme: "plain",
    margin: tableMargin,
    styles: { fontSize: 9, cellPadding: { top: 0.8, bottom: 0.8, left: 0 } },
    columnStyles: {
      0: { cellWidth: 30, fontStyle: "bold", textColor: 60 },
    },
    body: [
      ["Date range", rangeLabel],
      ["Window", input.filters.window],
      ["Action", input.filters.action],
      ["Search", input.filters.search || "None"],
      [
        "Generated",
        new Date().toLocaleString("en-PH", {
          dateStyle: "medium",
          timeStyle: "short",
        }),
      ],
      ["Generated by", input.generatedBy],
    ].map((row) => row.map(pdfText)),
  });

  // Summary
  let y = sectionHeading("Summary", lastTableY(doc) + 9);
  autoTable(doc, {
    startY: y,
    theme: "grid",
    margin: tableMargin,
    styles: { halign: "center", lineColor: 210 },
    headStyles: {
      fillColor: [241, 245, 249],
      textColor: 60,
      fontStyle: "normal",
      fontSize: 8,
    },
    bodyStyles: { fontSize: 14, fontStyle: "bold", textColor: 20 },
    head: [["Total Queues Created", "Total Processed", "Log Entries"]],
    body: [
      [
        String(input.summary.totalQueueCreated),
        String(input.summary.totalProcessed),
        String(input.rows.length),
      ],
    ],
  });

  // Log table, one block per local calendar day, oldest first.
  y = sectionHeading("Activity Log", lastTableY(doc) + 11);

  const sorted = [...input.rows].sort(
    (a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime(),
  );
  const days = new Map<string, ActivityLogPdfRow[]>();
  for (const row of sorted) {
    const key = dayKey(new Date(row.createdAt));
    const group = days.get(key);
    if (group) group.push(row);
    else days.set(key, [row]);
  }

  if (days.size === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    doc.text("No activity matches the selected filters.", MARGIN, y + 2);
  }

  for (const [key, group] of days) {
    const day = new Date(`${key}T00:00:00`);
    const weekday = day.toLocaleDateString("en-PH", { weekday: "short" });
    // Heading + table head + at least one row.
    y = ensureSpace(y, 24);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(20);
    doc.text(pdfText(`${formatDate(day)} (${weekday})`), MARGIN, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.text(
      `${group.length} action${group.length === 1 ? "" : "s"}`,
      pageWidth - MARGIN,
      y,
      { align: "right" },
    );

    autoTable(doc, {
      startY: y + 2.5,
      theme: "striped",
      margin: { ...tableMargin, top: MARGIN },
      showHead: "everyPage",
      rowPageBreak: "avoid",
      styles: { fontSize: 9, cellPadding: 2, overflow: "linebreak" },
      headStyles: { fillColor: HEAD_FILL, textColor: 255, fontStyle: "bold" },
      columnStyles: {
        0: { cellWidth: 22 },
        1: { cellWidth: 42 },
        2: { cellWidth: 32 },
      },
      head: [["Time", "Action", "Window", "Details"]],
      body: group.map((row) =>
        [
          new Date(row.createdAt).toLocaleTimeString("en-PH", {
            hour: "2-digit",
            minute: "2-digit",
          }),
          row.action,
          row.window,
          row.details,
        ].map(pdfText),
      ),
    });
    y = lastTableY(doc) + 10;
  }

  // Footer on every page, drawn last so the total page count is known.
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page++) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.setDrawColor(210);
    doc.line(MARGIN, pageHeight - 12, pageWidth - MARGIN, pageHeight - 12);
    doc.text(
      pdfText(`${input.officeLabel} · Activity Logs · ${rangeLabel}`),
      MARGIN,
      pageHeight - 8,
    );
    doc.text(`Page ${page} of ${pageCount}`, pageWidth - MARGIN, pageHeight - 8, {
      align: "right",
    });
  }

  return doc;
}
